//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_CHANGE = "LOGIN_CHANGE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
//TOPIC
export const SET_TOPIC = "SET_TOPIC"
//QUIZ
//RESULT